# vim: ft=python expandtab
import os
Import('env_glib_glib prefix')

env_glib_glib_test = env_glib_glib.Clone()
env_glib_glib_test.Append(LIBS='libglib-2.0')
env_glib_glib_test.Append(LIBPATH=['#glib/glib'])
env_glib_glib_test.Append(CFLAGS=env_glib_glib['DEBUG_CFLAGS'])
env_glib_glib_test['CPPDEFINES'] = env_glib_glib['DEBUG_CPPDEFINES']

tests = ["testing",
         "option-context",
         "keyfile",
         "fileutils",
         "printf",
         "rand",
         #"strfuncs", #glib\glib\tests\strfuncs.c(955) : fatal error C1064: compiler limit : token over flowed internal buffer
         "string",
         "markup-subparser",
         "array-test",
         "hostutils"]
for i in tests:
    e = env_glib_glib_test.Clone(PDB = i + '.pdb')
    e.Program(i, i + '.c')

for x in tests:
    if x not in ['']:
        env_glib_glib_test.AlwaysBuild(env_glib_glib_test.Alias('test', [], os.path.join('glib', 'glib', 'tests', x + '.exe')))
