# vim: ft=python expandtab

Import('env_glib')

# win_iconv
env_glib_libcharset = env_glib.Clone()
env_glib_libcharset.Append(CPPDEFINES=[('LIBDIR', '$PREFIX/lib')])
libcharset = env_glib_libcharset.StaticLibrary('libcharset', 'localcharset.c')

#Return(libcharset)
