# vim: ft=python expandtab
import os
Import('env_gio')

env_gio_test = env_gio.Clone()
env_gio_test.Append(CFLAGS=env_gio['DEBUG_CFLAGS'])
env_gio_test['CPPDEFINES'] = [('SRCDIR', r'\"\"')] + env_gio['DEBUG_CPPDEFINES'] #FIXME: os.path.dirname(__file__) complains __file__ is not defiend
env_gio_test.Append(CPPPATH=['#glib', '#glib', '#gmodule'])
env_gio_test.Append(LIBS=['libglib-2.0', 'libgthread-2.0', 'libgobject-2.0', 'libgio-2.0', 'user32'])
env_gio_test.Append(LIBPATH=['#glib', '#gthread', '#gobject', '#gio'])

tests = ["memory-input-stream",
         "memory-output-stream",
         "readwrite",
         "g-file",
         "g-file-info",
	 "converter-stream",
         "data-input-stream",
         "data-output-stream",
         "g-icon",
         "buffered-input-stream",
         "sleepy-stream",
         "filter-streams",
         "simple-async-result",
         "srvtarget",
         "contexts"]

sample_progs = Split("\
	resolver		\
	socket-server		\
	socket-client		\
	echo-server		\
	httpd			\
	send-data		\
	filter-cat")
for i in tests + sample_progs:
    e = env_gio_test.Clone(PDB = i + '.pdb')
    e.Program(i, i + '.c')
