# vim: ft=python expandtab
import os
Import('env_glib_gobject prefix')

env_glib_gobject_test = env_glib_gobject.Clone()
env_glib_gobject_test.Append(CFLAGS=env_glib_gobject['DEBUG_CFLAGS'])
env_glib_gobject_test['CPPDEFINES'] = env_glib_gobject['DEBUG_CPPDEFINES'] 
env_glib_gobject_test.Append(CPPPATH=['#glib', '#glib/glib', '#glib/gmodule'])
env_glib_gobject_test.Append(LIBS=['libglib-2.0', 'libgthread-2.0', 'libgobject-2.0',])
env_glib_gobject_test.Append(LIBPATH=['#glib/glib', '#glib/gthread', '#glib/gobject'])

tests = ["threadtests"]
for i in tests:
    e = env_glib_gobject_test.Clone(PDB = i + '.pdb')
    e.Program(i, i + '.c')
