# vim: ft=python expandtab
import os
Import('env_gobject')

env_gobject_test = env_gobject.Clone()
env_gobject_test.Append(CFLAGS=env_gobject['DEBUG_CFLAGS'])
env_gobject_test['CPPDEFINES'] = env_gobject['DEBUG_CPPDEFINES'] 
env_gobject_test.Append(CPPPATH=['#', '#glib', '#gmodule'])
env_gobject_test.Append(LIBS=['libglib-2.0', 'libgthread-2.0', 'libgobject-2.0',])
env_gobject_test.Append(LIBPATH=['#glib', '#gthread', '#gobject'])

tests = ["threadtests",
         "dynamictests"]
for i in tests:
    e = env_gobject_test.Clone(PDB = i + '.pdb')
    e.Program(i, i + '.c')
