# vim: ft=python expandtab

Import('env_gio')

#libgiowin32 
libgiowin32_SOURCES = Split("\
	gwin32directorymonitor.c		\
	gwinhttpvfs.c				\
	gwinhttpfile.c				\
	gwinhttpfileinputstream.c		\
	gwinhttpfileoutputstream.c")
env_gio.StaticLibrary('libgiowin32', libgiowin32_SOURCES)
