# vim: ft=python expandtab
from site_init import *

Import('env')

# 
env_libintl_proxy = env.Clone(PDB = 'libintl-proxy.pdb')
libintl_SOURCES = Split("libintl.c libintl.def")
libintl = env_libintl_proxy.SharedLibrary(['libintl-proxy' + env_libintl_proxy['LIB_SUFFIX'],
                                                'libintl-proxy.lib'], libintl_SOURCES)
env_libintl_proxy.AddPostAction(libintl, 'mt.exe -nologo -manifest ${TARGET}.manifest -outputresource:$TARGET;2')

InstallRun('$PREFIX/bin', 'libintl-proxy'+env_libintl_proxy['LIB_SUFFIX'] + env_libintl_proxy['SHLIBSUFFIX'], env_libintl_proxy)
InstallRun('$PREFIX/bin', 'intl.dll', env_libintl_proxy)
InstallDev('$PREFIX/include/glib-2.0', 'libintl.h', env_libintl_proxy)
InstallDev('$PREFIX/lib', 'libintl-proxy.lib', env_libintl_proxy)
InstallDevAs('$PREFIX/lib/intl-proxy.lib', 'libintl-proxy.lib', env_libintl_proxy)
